export interface Post {
  postId: string;
  userId: string;
  nickname?: string; // User's display name from Cognito
  content: string;
  createdAt: string;
  imageUrl?: string; // Signed S3 URL (generated by listPosts) - deprecated, use imageUrls
  imageUrls?: string[]; // Multiple signed S3 URLs (max 10)
  isMarkdown?: boolean; // Whether content uses Markdown formatting
  tags?: string[]; // Tags for categorization and search
}

export interface PostItem extends Post {
  PK: string;
  SK: string;
  imageKey?: string; // S3 key (stored in DynamoDB) - deprecated, use imageKeys
  imageKeys?: string[]; // Multiple S3 keys (max 10)
}

export interface CreatePostBody {
  content?: string;
  image?: string; // Base64 encoded image data - deprecated, use images
  images?: string[]; // Multiple base64 encoded images (max 10)
  isMarkdown?: boolean; // Whether content uses Markdown formatting
  tags?: string[]; // Space-separated tags (max 100)
}

export interface ListPostsResponse {
  items: Post[];
  limit: number;
  nextToken?: string;
}

export interface UserProfile {
  userId: string;
  nickname?: string;
  updatedAt?: string;
  createdAt?: string;
}

export interface ErrorResponse {
  message: string;
}
