#!/bin/bash
# satoshiユーザーでのAWSプロファイル設定ガイド

echo "================================================"
echo "satoshiユーザーのAWS CLIプロファイル設定"
echo "================================================"
echo ""
echo "既存のアクセスキーID: AKIAUBSWPOCGNDK6KNVL"
echo ""
echo "以下のコマンドでプロファイルを設定してください："
echo ""
echo "  aws configure --profile satoshi"
echo ""
echo "入力が必要な情報："
echo "  AWS Access Key ID: (既存のキーまたは新規作成したキー)"
echo "  AWS Secret Access Key: (対応するシークレットキー)"
echo "  Default region name: us-east-1"
echo "  Default output format: json"
echo ""
echo "================================================"
echo ""
echo "新しいアクセスキーが必要な場合（管理者アカウントで実行）："
echo ""
echo "  # 古いキーを無効化"
echo "  aws iam update-access-key --user-name satoshi \\"
echo "    --access-key-id AKIAUBSWPOCGNDK6KNVL --status Inactive"
echo ""
echo "  # 新しいキーを作成"
echo "  aws iam create-access-key --user-name satoshi"
echo ""
echo "================================================"
